# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'git@git.2dfire-inc.com:ios/cocoapods-spec.git'

target 'TDFScreenDebuggerExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#  use_frameworks!

  # Pods for TDFScreenDebuggerExample
  pod 'TDFScreenDebugger', :path => '../'

  target 'TDFScreenDebuggerExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

